---

  - hosts: all
    become: yes
    become_user: root
    remote_user: vagrant

    tasks:
      - name: Create directory for ssh-keys
        file: state=directory mode=0700 dest=/root/.ssh/
      - name: Create directory for kube
        file: state=directory mode=0710 dest=/home/vagrant/.kube owner=vagrant group=vagrant
      - name: Installing snapd package
        apt: >
          name={{ item }}
          state=present
          update_cache=yes
        with_items:
          - snapd
      - name: Installing microk8s package
        community.general.snap:
          name: microk8s
          classic: yes
      - name: adding existing user vagrant to group microk8s
        user:
          name: vagrant
          groups: microk8s
          append: yes
      - name: Add external access
        ansible.builtin.lineinfile:
          path: /var/snap/microk8s/current/certs/csr.conf.template
          regexp: '^IP.3'
          insertafter: '^IP.2'
          line: IP.3 = {{ansible_eth1.ipv4.address}}
        register: add_ip
      - name: microk8s refresh-certs
        ansible.builtin.shell: microk8s refresh-certs --cert front-proxy-client.crt
        register: update_certs
        ignore_errors: true
        when: add_ip.changed == true
      - name:  enable dashboard
        ansible.builtin.shell: microk8s enable dashboard
        ignore_errors: true
      - name: Create token for dashboard
        ansible.builtin.shell: microk8s kubectl describe secret -n kube-system microk8s-dashboard-token
      - name: Create token for dashboard
        ansible.builtin.shell: microk8s kubectl get secret microk8s-dashboard-token  -n kube-system -o jsonpath={".data.token"} | base64 -d
        register: dash_token
      - debug:
           msg:
           - "dash_token = {{dash_token.stdout}}"
           - "ip = {{ansible_eth1.ipv4.address}}"





