apiVersion: v1
kind: Service
metadata:
  name: hw-12-1-4-2
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: svc-nginx-http
    protocol: TCP
    port: 9001
    targetPort: nginx-http
    nodePort: 30081
  - name: svc-mtool-http
    protocol: TCP
    port: 9002
    targetPort: mtool-http
    nodePort: 30082
