---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
  - name: Print fed
    hosts: fed
    tasks:
      - name: Print ssh_port
        debug:
          msg: "{{ ssh_port }}"