---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_host: 62.84.114.32
      ansible_user: centos
vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_host: 158.160.59.95
      ansible_user: centos
lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: ssh
      ansible_host: 158.160.36.161
      ansible_user: centos