---
all:
  hosts:
    jenkins-master-01:
      ansible_port: 20011
    jenkins-agent-01:
      ansible_port: 20012
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_host: 127.0.0.1
    ansible_connection_type: paramiko
    ansible_user: vagrant